CREATE TABLE IF NOT EXISTS trusted_devices (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  token_hash CHAR(128) NOT NULL,
  device_label VARCHAR(150) DEFAULT NULL,
  user_agent TEXT DEFAULT NULL,
  client_hints VARCHAR(255) DEFAULT NULL,
  ip_address VARCHAR(45) DEFAULT NULL,
  accept_language VARCHAR(120) DEFAULT NULL,
  fingerprint VARCHAR(128) DEFAULT NULL,
  extra_metadata TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_used_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  revoked_at DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_trusted_devices_token (token_hash),
  KEY idx_trusted_devices_user (user_id),
  KEY idx_trusted_devices_valid (user_id, revoked_at, expires_at),
  CONSTRAINT fk_trusted_devices_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
