CREATE TABLE IF NOT EXISTS license_status (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  paid_until DATE NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO license_status (id, paid_until)
VALUES (1, CURDATE())
ON DUPLICATE KEY UPDATE paid_until = VALUES(paid_until);
